
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadorfca;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cierre_parentesis = 25;
  public static final int cadena = 30;
  public static final int decimal = 29;
  public static final int apertura_llave = 20;
  public static final int titulo_ejey = 12;
  public static final int titulo_ejex = 11;
  public static final int coma = 28;
  public static final int generar_reporte_estadistico = 3;
  public static final int titulo_grafica = 9;
  public static final int archivo_grafica_lineas = 14;
  public static final int cierre_llave = 21;
  public static final int grafica_de_barras = 6;
  public static final int valores_grafica = 13;
  public static final int comparar = 4;
  public static final int dos_puntos = 27;
  public static final int apertura_corchete = 22;
  public static final int ejex = 10;
  public static final int igual = 26;
  public static final int EOF = 0;
  public static final int puntaje_especifico = 19;
  public static final int id = 31;
  public static final int puntaje_general = 18;
  public static final int error = 1;
  public static final int grafica_de_lineas = 8;
  public static final int cierre_corchete = 23;
  public static final int fin_de_linea = 2;
  public static final int grafica_de_pie = 7;
  public static final int definir_globales = 5;
  public static final int apertura_parentesis = 24;
  public static final int concatenacion = 17;
  public static final int tipo_de_dato_double = 16;
  public static final int tipo_de_dato_string = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "fin_de_linea",
  "generar_reporte_estadistico",
  "comparar",
  "definir_globales",
  "grafica_de_barras",
  "grafica_de_pie",
  "grafica_de_lineas",
  "titulo_grafica",
  "ejex",
  "titulo_ejex",
  "titulo_ejey",
  "valores_grafica",
  "archivo_grafica_lineas",
  "tipo_de_dato_string",
  "tipo_de_dato_double",
  "concatenacion",
  "puntaje_general",
  "puntaje_especifico",
  "apertura_llave",
  "cierre_llave",
  "apertura_corchete",
  "cierre_corchete",
  "apertura_parentesis",
  "cierre_parentesis",
  "igual",
  "dos_puntos",
  "coma",
  "decimal",
  "cadena",
  "id"
  };
}

