
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadorjs;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int false_t = 24;
  public static final int suma_doble = 43;
  public static final int fin_de_linea = 30;
  public static final int if_t = 34;
  public static final int suma = 14;
  public static final int resta = 15;
  public static final int mayor_que = 8;
  public static final int switch_t = 40;
  public static final int cierre_parentesis = 26;
  public static final int coma = 3;
  public static final int igual = 2;
  public static final int comentario_multi = 48;
  public static final int for_t = 37;
  public static final int multiplicacion = 16;
  public static final int diferencia = 6;
  public static final int dos_puntos = 4;
  public static final int igualacion = 5;
  public static final int menor_que = 7;
  public static final int iden = 22;
  public static final int importar = 29;
  public static final int comentsimple = 47;
  public static final int default_t = 42;
  public static final int EOF = 0;
  public static final int mayor_igual = 10;
  public static final int consola = 33;
  public static final int error = 1;
  public static final int apertura_llave = 27;
  public static final int apertura_parentesis = 25;
  public static final int or = 12;
  public static final int while_t = 38;
  public static final int else_if = 36;
  public static final int menor_igual = 9;
  public static final int break_t = 45;
  public static final int resta_doble = 44;
  public static final int definir_clase = 46;
  public static final int potencia = 18;
  public static final int true_t = 23;
  public static final int and = 11;
  public static final int salto = 31;
  public static final int not = 13;
  public static final int case_t = 41;
  public static final int else_t = 35;
  public static final int definir_variable = 32;
  public static final int cierre_llave = 28;
  public static final int division = 17;
  public static final int modulo = 19;
  public static final int decimal = 20;
  public static final int do_t = 39;
  public static final int cadena = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "igual",
  "coma",
  "dos_puntos",
  "igualacion",
  "diferencia",
  "menor_que",
  "mayor_que",
  "menor_igual",
  "mayor_igual",
  "and",
  "or",
  "not",
  "suma",
  "resta",
  "multiplicacion",
  "division",
  "potencia",
  "modulo",
  "decimal",
  "cadena",
  "iden",
  "true_t",
  "false_t",
  "apertura_parentesis",
  "cierre_parentesis",
  "apertura_llave",
  "cierre_llave",
  "importar",
  "fin_de_linea",
  "salto",
  "definir_variable",
  "consola",
  "if_t",
  "else_t",
  "else_if",
  "for_t",
  "while_t",
  "do_t",
  "switch_t",
  "case_t",
  "default_t",
  "suma_doble",
  "resta_doble",
  "break_t",
  "definir_clase",
  "comentsimple",
  "comentario_multi"
  };
}

